package com.strava.domain

case class Activity(id: Long,
                    resource_state: Int,
                    external_id: Option[String] = None,
                    upload_id: Option[Int] = None,
                    athlete: Athlete,
                    name: String,
                    description: Option[String] = None,
                    distance: Float,
                    moving_time: Int,
                    elapsed_time: Int,
                    total_elevation_gain: Float,
                    `type`: String,
                    start_date: String,
                    start_date_local: String,
                    timezone: String,
                    start_latlng: Seq[Float] = Seq.empty,
                    end_latlng: Seq[Float] = Seq.empty,
                    location_city: Option[String] = None,
                    location_state: Option[String] = None,
                    location_country: Option[String] = None,
                    achievement_count: Int,
                    kudos_count: Int,
                    comment_count: Int,
                    athlete_count: Int,
                    photo_count: Int,
                    map: Polyline,
                    trainer: Boolean,
                    commute: Boolean,
                    manual: Boolean,
                    `private`: Boolean,
                    flagged: Boolean,
                    workout_type: Option[Int] = None,
                    gear_id: Option[String] = None,
                    gear: Option[Gear] = None,
                    average_speed: Float,
                    max_speed: Float,
                    average_cadence: Option[Float] = None,
                    average_temp: Option[Int] = None,
                    average_watts: Option[Int] = None,
                    weighted_average_watts: Option[Int] = None,
                    kilojoules: Option[Float] = None,
                    device_watts: Option[Boolean] = None,
                    average_heartrate: Option[Float] = None,
                    max_heartrate: Option[Float] = None,
                    calories: Option[Float] = None,
                    truncated: Option[Int] = None,
                    has_kudoed: Boolean,
                    segmentEfforts: Seq[SegmentEffort] = Seq.empty,
                    splitsMetric: Seq[SplitMetrics] = Seq.empty,
                    splitsStandard: Seq[SplitStandard] = Seq.empty,
                    bestEfforts: Seq[SegmentEffort] = Seq.empty)